spring:
  application:
    name: TwitterToKafkaService
twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Spring Boot
    - Kafka
    - Elasticsearch
    - Microservices
  welcome-message: Welcome to TwitterToKafkaService
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
